import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SEO from "../seo.config";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import CleanBodyAttr from "./components/CleanBodyAttr.client";
import Script from 'next/script';
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isDev = process.env.NODE_ENV === 'development';
  return (
    <html lang="en" suppressHydrationWarning={isDev}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>{SEO.defaultTitle}</title>
        <meta name="description" content={SEO.description} />
        <link rel="canonical" href={SEO.canonical} />
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#ffffff" />
        <meta name="application-name" content={SEO.openGraph.siteName} />
        <meta name="author" content="Obi Tobechukwu" />
        <meta name="attribution" content="Cute icons created by Smashicons - Flaticon https://www.flaticon.com/free-icons/cute" />

        {/* Open Graph */}
        <meta property="og:title" content={SEO.defaultTitle} />
        <meta property="og:description" content={SEO.description} />
        <meta property="og:type" content={SEO.openGraph.type} />
        <meta property="og:locale" content={SEO.openGraph.locale} />
        <meta property="og:site_name" content={SEO.openGraph.siteName} />
        <meta property="og:url" content={SEO.openGraph.url} />
        {SEO.openGraph.images && SEO.openGraph.images[0] && (
          <meta property="og:image" content={SEO.openGraph.images[0].url} />
        )}

        {/* Twitter */}
        <meta name="twitter:card" content={SEO.twitter.cardType} />
        <meta name="twitter:site" content={SEO.twitter.site} />
        <meta name="twitter:creator" content={SEO.twitter.handle} />

        {/* Run before React hydration to remove extension-injected attributes */}
        <Script id="cleanup-cz-attrs" strategy="beforeInteractive">
{`try{(function(){var r=document.documentElement,c=document.body; if(r&&r.getAttributeNames){r.getAttributeNames().forEach(function(n){ if(n&&n.startsWith('cz-')) r.removeAttribute(n); }); } if(c&&c.getAttributeNames){c.getAttributeNames().forEach(function(n){ if(n&&n.startsWith('cz-')) c.removeAttribute(n); }); }})();}catch(e){}`}
        </Script>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={isDev}
      >
        {/* Client-side cleanup (keeps acting after mount as a fallback) */}
        <CleanBodyAttr />
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Navbar />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
